### ISSUE TITLE
usage checks

### ISSUE THREAD

**Issue by snopoke** [dimagi/commcare_resource_model#16]
Specify actual usage data at certain dates to allow checking the model against. When running the model it would output another sheet comparing actual usage with predicted usage:

```yaml
actual_usage:
  20190101:
    forms_total: X
    cases_total: Y
```
